# Generated by Django 5.2.3 on 2025-06-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_item_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('collection_name', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_image', models.ImageField(blank=True, null=True, upload_to='collection/')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collection'),
        ),
    ]
